server:
  port: 9010

spring:
  application:
    name: redisson
  redis:
    port: 6379
    host: 192.168.32.128
    password:
    database: 0
    timeout: 2000
  redisson:
    host: 192.168.32.207:6379
    password:
    database: 0
    timeout: 2000